#!/bin/bash

set -eu
set -o pipefail

# Detect the OS
if [ $(uname -s) == "Linux" ]; then
    DISTRO="$(cat /etc/os-release | grep -E '^ID=' | cut -d '=' -f 2 | sed 's/"//g')"
    case "$DISTRO" in
        "arch" | "endeavouros" | "manjaro")
            OS="arch"
            PACKAGE_MANAGER="pacman"
            ;;
        "ubuntu" | "debian")
            OS="debian"
            PACKAGE_MANAGER="apt"
            ;;
        *)
            echo "Unsupported linux distro: $DISTRO. Packages won't be installed automatically."
            ;;
    esac
else
    echo "Unsupported OS: $(uname -s). Packages won't be installed automatically."
fi

if [ -n "${OS+x}" ]; then
    echo "Detected OS: $OS"
    echo "Package manager: $PACKAGE_MANAGER"
fi

# Ensure ~/.config exists
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ ! -d "$CONFIG" ]; then
    echo "Creating $CONFIG..."
    mkdir -p "$CONFIG"
fi

# Install required packages if a package manager was detected
if [ -n "${PACKAGE_MANAGER+x}" ]; then
    echo "Installing required packages. If prompted by sudo, please enter your password."
    case "$PACKAGE_MANAGER" in
        "pacman")
            sudo pacman -Sy --noconfirm --needed fish git git-crypt stow tmux direnv zoxide vim
            ;;
        "apt")
            sudo apt-get update
            sudo apt-get install -y fish git git-crypt stow tmux direnv zoxide vim
            ;;
        *)
            echo "Unsupported package manager: $PACKAGE_MANAGER. Packages won't be installed automatically."
            ;;
    esac
fi

# Install dotfiles
echo "Installing dotfiles..."
stow -v 2 .

# Try to decrypt using keys from the GPG keyring
# If this fails the user has to manually provide a symmetric key or try to decrypt secrets again
git crypt unlock

# Set fish as the default shell
echo "Setting fish as the default shell..."
sudo chsh -s "$(which fish)" "$USER"

# Install mise
# https://mise.jdx.dev/installing-mise.html#https-mise-run
curl https://mise.run | sh
fish_add_path "$HOME/.local/bin"

# Install TPM and tmux plugins
TMUX_DIR="$CONFIG/tmux"
TPM_DIR="$TMUX_DIR/plugins/tpm"
if [ ! -d "$TPM_DIR" ]; then
    echo "Installing TPM..."
    mkdir -p "$TMUX_DIR/plugins"
    git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
else
    echo "TPM already installed."
fi
echo "Installing TPM plugins..."
"$TPM_DIR/bin/install_plugins"
