name: Test Install Script

on:
  push:

jobs:
  test-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run install script
        run: |
          chmod u+x ./install
          ./install

      # TODO: Some tests
